### ISSUE TITLE
ELM accession numbers to add to metatable

### ISSUE THREAD

**Issue by elenapapaleo** [ELELAB/cancermuts#147]
for easier interepretation of the results in the metatable would be convenient to add a column with the accession number of the motifs identified for each site. Once you have found overlap with a SLiM of interest, the first natural thing to do is to go back to ELM and read the documentation on that specific motif, the accession number will facilitate the query.

**Comment by mtiberti** [comment]
good point! And it shouldn't be difficult to add

**Comment by elenapapaleo** [comment]
isn't this the same of issue 79
