### ISSUE TITLE
problems with genes with '-' in the name

### ISSUE THREAD

**Issue by elenapapaleo** [ELELAB/cancermuts#150]
as an example MT-CYB will not work with the current setup (example can be seen and rerun to reproduce the error in our local cancermuts_data repository)

**Comment by mtiberti** [comment]
Traceback:

```
  File "/usr/local/envs/cancermuts/lib/python3.8/site-packages/cancermuts-0.1-py3.8.egg/cancermuts/datasources.py", line 261, in add_mutations
    mutations, out_metadata = self._get_available_mutations(sequence.aliases['entrez'], metadata=metadata)
  File "/usr/local/envs/cancermuts/lib/python3.8/site-packages/cancermuts-0.1-py3.8.egg/cancermuts/datasources.py", line 474, in _get_available_mutations
    gd = ['hg19', str(int(gd[0])), str(int(gd[1])), str(int(gd[2])), str(gd[3])]
ValueError: invalid literal for int() with base 10: 'MT'
```

**Comment by mtiberti** [comment]
This happens because the gene is actually on the mitochondrial genome which we currently don't support. We should make it clear in the documentation. Plus this problem might affect genes on the X/Y chromosome, we should run some tests

**Comment by mtiberti** [comment]
just to have an overview
  - both cBioPortal and COSMIC store mutations for mitochondrial genes. 
  - REVEL and gNOMAD do not support them

**Comment by elenapapaleo** [comment]
I think we can avoid to support them for now but we will reopen this if it is needed
